"""SQLAlchemy ORM models for JARVIS relational memory.

These models live alongside the existing raw-sqlite memory store and use
separate table names so there is no collision.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, relationship


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_id() -> str:
    return uuid.uuid4().hex


class Base(DeclarativeBase):
    """Declarative base for all SQLAlchemy models."""

    pass


class UserPreference(Base):
    """Structured user preferences with categories and typing."""

    __tablename__ = "user_preferences"

    id = Column(String(32), primary_key=True, default=_new_id)
    key = Column(String(255), nullable=False, unique=True)
    value = Column(Text, nullable=False, default="")
    # Optional JSON payload for complex preference values.
    json_value = Column(JSON, nullable=True)
    category = Column(String(64), nullable=False, default="general")
    description = Column(Text, nullable=True)
    updated_at = Column(DateTime, nullable=False, default=_utcnow, onupdate=_utcnow)

    def __repr__(self) -> str:
        return f"<UserPreference key={self.key!r} category={self.category!r}>"


class Project(Base):
    """A project managed by the assistant."""

    __tablename__ = "projects"

    id = Column(String(32), primary_key=True, default=_new_id)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    status = Column(String(32), nullable=False, default="active")
    # Arbitrary metadata (labels, paths, settings).
    metadata_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, nullable=False, default=_utcnow)
    updated_at = Column(DateTime, nullable=False, default=_utcnow, onupdate=_utcnow)

    tasks = relationship("Task", back_populates="project", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Project name={self.name!r} status={self.status!r}>"


class Task(Base):
    """A task belonging to a project."""

    __tablename__ = "tasks"

    id = Column(String(32), primary_key=True, default=_new_id)
    project_id = Column(String(32), ForeignKey("projects.id"), nullable=False)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    status = Column(String(32), nullable=False, default="pending")
    priority = Column(String(32), nullable=False, default="medium")
    # Arbitrary metadata (assignee, due date, labels).
    metadata_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, nullable=False, default=_utcnow)
    updated_at = Column(DateTime, nullable=False, default=_utcnow, onupdate=_utcnow)

    project = relationship("Project", back_populates="tasks")

    def __repr__(self) -> str:
        return f"<Task title={self.title!r} status={self.status!r}>"


class ConversationMetadata(Base):
    """Extended metadata for a conversation (complements raw SQLite conversations)."""

    __tablename__ = "conversation_metadata"

    id = Column(String(32), primary_key=True)
    # Mirror the raw conversations.id so lookups are fast.
    conversation_id = Column(String(32), nullable=False, unique=True)
    # The surface/channel that created this conversation.
    channel = Column(String(64), nullable=False, default="cli")
    # Optional user-given title override.
    title_override = Column(String(255), nullable=True)
    # Summary generated by the agent (for long conversations).
    summary = Column(Text, nullable=True)
    # Total message count (cached for quick stats).
    message_count = Column(Integer, nullable=False, default=0)
    # Total token usage estimate (if available from the provider).
    token_usage = Column(Integer, nullable=False, default=0)
    # Arbitrary tags / labels.
    tags = Column(JSON, nullable=True)
    archived = Column(Integer, nullable=False, default=0)
    created_at = Column(DateTime, nullable=False, default=_utcnow)
    updated_at = Column(DateTime, nullable=False, default=_utcnow, onupdate=_utcnow)

    def __repr__(self) -> str:
        return f"<ConversationMetadata channel={self.channel!r} message_count={self.message_count}>"
